#!/bin/bash
set -e

mysql --local-infile=1 -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE <<EOF

USE tpch;



LOAD DATA LOCAL INFILE '/data/region.tbl'
INTO TABLE Region
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '/data/nation.tbl'
INTO TABLE Nation
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '/data/supplier.tbl'
INTO TABLE Supplier
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '/data/part.tbl'
INTO TABLE Part
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '/data/partsupp.tbl'
INTO TABLE Partsupp
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '/data/customer.tbl'
INTO TABLE Customer
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '/data/orders.tbl'
INTO TABLE Orders
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '/data/lineitem.tbl'
INTO TABLE Lineitem
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';


EOF